(cl:in-package mobileye_560_660_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BOUNDARY_DOMAIN_BOTTOM_NON_GLARE_HLB-VAL
          BOUNDARY_DOMAIN_BOTTOM_NON_GLARE_HLB
          BOUNDARY_DOMAIN_NON_GLARE_LEFT_HAND_HLB-VAL
          BOUNDARY_DOMAIN_NON_GLARE_LEFT_HAND_HLB
          BOUNDARY_DOMAIN_NON_GLARE_RIGHT_HAND_HLB-VAL
          BOUNDARY_DOMAIN_NON_GLARE_RIGHT_HAND_HLB
          OBJECT_DISTANCE_HLB-VAL
          OBJECT_DISTANCE_HLB
          STATUS_BOUNDARY_DOMAIN_BOTTOM_NON_GLARE_HLB-VAL
          STATUS_BOUNDARY_DOMAIN_BOTTOM_NON_GLARE_HLB
          STATUS_BOUNDARY_DOMAIN_NON_GLARE_LEFT_HAND_HLB-VAL
          STATUS_BOUNDARY_DOMAIN_NON_GLARE_LEFT_HAND_HLB
          STATUS_BOUNDARY_DOMAIN_NON_GLARE_RIGHT_HAND_HLB-VAL
          STATUS_BOUNDARY_DOMAIN_NON_GLARE_RIGHT_HAND_HLB
          STATUS_OBJECT_DISTANCE_HLB-VAL
          STATUS_OBJECT_DISTANCE_HLB
          LEFT_TARGET_CHANGE-VAL
          LEFT_TARGET_CHANGE
          RIGHT_TARGET_CHANGE-VAL
          RIGHT_TARGET_CHANGE
          TOO_MANY_CARS-VAL
          TOO_MANY_CARS
          BUSY_SCENE-VAL
          BUSY_SCENE
))