(cl:in-package mobileye_560_660_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SUPPRESS_SOUND-VAL
          SUPPRESS_SOUND
          NIGHT_TIME-VAL
          NIGHT_TIME
          DUSK_TIME-VAL
          DUSK_TIME
          SOUND_TYPE-VAL
          SOUND_TYPE
          HEADWAY_VALID-VAL
          HEADWAY_VALID
          HEADWAY_MEASUREMENT-VAL
          HEADWAY_MEASUREMENT
          LANES_ON-VAL
          LANES_ON
          LEFT_LDW_ON-VAL
          LEFT_LDW_ON
          RIGHT_LDW_ON-VAL
          RIGHT_LDW_ON
          FCW_ON-VAL
          FCW_ON
          LEFT_CROSSING-VAL
          LEFT_CROSSING
          RIGHT_CROSSING-VAL
          RIGHT_CROSSING
          MAINTENANCE-VAL
          MAINTENANCE
          FAILSAFE-VAL
          FAILSAFE
          PED_FCW-VAL
          PED_FCW
          PED_IN_DZ-VAL
          PED_IN_DZ
          HEADWAY_WARNING_LEVEL-VAL
          HEADWAY_WARNING_LEVEL
))