(cl:in-package mobileye_560_660_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VISION_ONLY_SIGN_TYPE_DISPLAY1-VAL
          VISION_ONLY_SIGN_TYPE_DISPLAY1
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY1-VAL
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY1
          VISION_ONLY_SIGN_TYPE_DISPLAY2-VAL
          VISION_ONLY_SIGN_TYPE_DISPLAY2
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY2-VAL
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY2
          VISION_ONLY_SIGN_TYPE_DISPLAY3-VAL
          VISION_ONLY_SIGN_TYPE_DISPLAY3
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY3-VAL
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY3
          VISION_ONLY_SIGN_TYPE_DISPLAY4-VAL
          VISION_ONLY_SIGN_TYPE_DISPLAY4
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY4-VAL
          VISION_ONLY_SUPPLEMENTARY_SIGN_TYPE_DISPLAY4
))