(cl:in-package kartech_linear_actuator_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SHAFT_EXTENSION-VAL
          SHAFT_EXTENSION
          MOTOR_OVERLOAD_ERROR-VAL
          MOTOR_OVERLOAD_ERROR
          CLUTCH_OVERLOAD_ERROR-VAL
          CLUTCH_OVERLOAD_ERROR
          MOTOR_OPEN_LOAD_ERROR-VAL
          MOTOR_OPEN_LOAD_ERROR
          CLUTCH_OPEN_LOAD_ERROR-VAL
          CLUTCH_OPEN_LOAD_ERROR
          POSITION_REACH_ERROR-VAL
          POSITION_REACH_ERROR
          HARDWARE_WARNING_1_ERROR-VAL
          HARDWARE_WARNING_1_ERROR
          HARDWARE_WARNING_2_ERROR-VAL
          HARDWARE_WARNING_2_ERROR
          MOTOR_CURRENT-VAL
          MOTOR_CURRENT
))