import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {Toaster} from "@/components/ui/sonner";
import {MobileNav} from "@/components/mobile-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="dark" suppressHydrationWarning>
        <body className={`${geistMono.className} ${geistSans.className} bg-neutral-950 text-neutral-100`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
            <div className="pb-16">{children}</div>
            <MobileNav />
            <Toaster
                theme="dark"
                position="top-right"
                toastOptions={{
                    className: "bg-neutral-800 text-neutral-100 border-neutral-700",
                    style: {
                        background: "#262626",
                        color: "#f5f5f5",
                        border: "1px solid #404040",
                    },
                }}
            />
        </ThemeProvider>
        </body>
        </html>
    )
}
