(cl:in-package delphi_esr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANMSG-VAL
          CANMSG
          TRUCK_TARGET_DET-VAL
          TRUCK_TARGET_DET
          LR_ONLY_GRATING_LOBE_DET-VAL
          LR_ONLY_GRATING_LOBE_DET
          SIDELOBE_BLOCKAGE-VAL
          SIDELOBE_BLOCKAGE
          PARTIAL_BLOCKAGE-VAL
          PARTIAL_BLOCKAGE
          MR_LR_MODE-VAL
          MR_LR_MODE
          ROLLING_COUNT_3-VAL
          ROLLING_COUNT_3
          PATH_ID_ACC-VAL
          PATH_ID_ACC
          PATH_ID_CMBB_MOVE-VAL
          PATH_ID_CMBB_MOVE
          PATH_ID_CMBB_STAT-VAL
          PATH_ID_CMBB_STAT
          PATH_ID_FCW_MOVE-VAL
          PATH_ID_FCW_MOVE
          PATH_ID_FCW_STAT-VAL
          PATH_ID_FCW_STAT
          AUTO_ALIGN_ANGLE-VAL
          AUTO_ALIGN_ANGLE
          PATH_ID_ACC_STAT-VAL
          PATH_ID_ACC_STAT
))