(cl:in-package delphi_esr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VEHICLE_SPEED-VAL
          VEHICLE_SPEED
          VEHICLE_SPEED_DIRECTION-VAL
          VEHICLE_SPEED_DIRECTION
          YAW_RATE-VAL
          YAW_RATE
          YAW_RATE_VALIDITY-VAL
          YAW_RATE_VALIDITY
          STEERING_ANGLE_RATE_SIGN-VAL
          STEERING_ANGLE_RATE_SIGN
          RADIUS_CURVATURE-VAL
          RADIUS_CURVATURE
          STEERING_ANGLE_VALIDITY-VAL
          STEERING_ANGLE_VALIDITY
          STEERING_ANGLE_SIGN-VAL
          STEERING_ANGLE_SIGN
          STEERING_ANGLE-VAL
          STEERING_ANGLE
          STEERING_ANGLE_RATE-VAL
          STEERING_ANGLE_RATE
))