(cl:in-package delphi_esr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANMSG-VAL
          CANMSG
          MAXIMUM_TRACKS_ACK-VAL
          MAXIMUM_TRACKS_ACK
          ROLLING_COUNT_2-VAL
          ROLLING_COUNT_2
          OVERHEAT_ERROR-VAL
          OVERHEAT_ERROR
          RANGE_PERF_ERROR-VAL
          RANGE_PERF_ERROR
          INTERNAL_ERROR-VAL
          INTERNAL_ERROR
          XCVR_OPERATIONAL-VAL
          XCVR_OPERATIONAL
          RAW_DATA_MODE-VAL
          RAW_DATA_MODE
          STEERING_ANGLE_ACK-VAL
          STEERING_ANGLE_ACK
          TEMPERATURE-VAL
          TEMPERATURE
          VEH_SPD_COMP_FACTOR-VAL
          VEH_SPD_COMP_FACTOR
          GROUPING_MODE-VAL
          GROUPING_MODE
          YAW_RATE_BIAS-VAL
          YAW_RATE_BIAS
          SW_VERSION_DSP-VAL
          SW_VERSION_DSP
))