(cl:in-package delphi_esr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANMSG-VAL
          CANMSG
          ID-VAL
          ID
          LAT_RATE-VAL
          LAT_RATE
          GROUPING_CHANGED-VAL
          GROUPING_CHANGED
          ONCOMING-VAL
          ONCOMING
          STATUS-VAL
          STATUS
          ANGLE-VAL
          ANGLE
          RANGE-VAL
          RANGE
          BRIDGE_OBJECT-VAL
          BRIDGE_OBJECT
          ROLLING_COUNT-VAL
          ROLLING_COUNT
          WIDTH-VAL
          WIDTH
          RANGE_ACCEL-VAL
          RANGE_ACCEL
          MED_RANGE_MODE-VAL
          MED_RANGE_MODE
          RANGE_RATE-VAL
          RANGE_RATE
))