// Generated by gencpp from file radar_msgs/RadarTracks.msg
// DO NOT EDIT!


#ifndef RADAR_MSGS_MESSAGE_RADARTRACKS_H
#define RADAR_MSGS_MESSAGE_RADARTRACKS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <radar_msgs/RadarTrack.h>

namespace radar_msgs
{
template <class ContainerAllocator>
struct RadarTracks_
{
  typedef RadarTracks_<ContainerAllocator> Type;

  RadarTracks_()
    : header()
    , tracks()  {
    }
  RadarTracks_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tracks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::radar_msgs::RadarTrack_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::radar_msgs::RadarTrack_<ContainerAllocator> >> _tracks_type;
  _tracks_type tracks;





  typedef boost::shared_ptr< ::radar_msgs::RadarTracks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::radar_msgs::RadarTracks_<ContainerAllocator> const> ConstPtr;

}; // struct RadarTracks_

typedef ::radar_msgs::RadarTracks_<std::allocator<void> > RadarTracks;

typedef boost::shared_ptr< ::radar_msgs::RadarTracks > RadarTracksPtr;
typedef boost::shared_ptr< ::radar_msgs::RadarTracks const> RadarTracksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::radar_msgs::RadarTracks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::radar_msgs::RadarTracks_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::radar_msgs::RadarTracks_<ContainerAllocator1> & lhs, const ::radar_msgs::RadarTracks_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tracks == rhs.tracks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::radar_msgs::RadarTracks_<ContainerAllocator1> & lhs, const ::radar_msgs::RadarTracks_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace radar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RadarTracks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::radar_msgs::RadarTracks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RadarTracks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::radar_msgs::RadarTracks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RadarTracks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::radar_msgs::RadarTracks_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::radar_msgs::RadarTracks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d068321616577632690aba69b8985e75";
  }

  static const char* value(const ::radar_msgs::RadarTracks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd068321616577632ULL;
  static const uint64_t static_value2 = 0x690aba69b8985e75ULL;
};

template<class ContainerAllocator>
struct DataType< ::radar_msgs::RadarTracks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "radar_msgs/RadarTracks";
  }

  static const char* value(const ::radar_msgs::RadarTracks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::radar_msgs::RadarTracks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"radar_msgs/RadarTrack[] tracks\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: radar_msgs/RadarTrack\n"
"# This message relates only to FMCW radar.  \n"
"# All variables below are relative to the radar's frame of reference.\n"
"# This message is not meant to be used alone but as part of a stamped or array message.\n"
"\n"
"# Object classifications (Additional vendor-specific classifications are permitted starting from 32000 eg. Car)\n"
"uint16 NO_CLASSIFICATION=0\n"
"uint16 STATIC=1\n"
"uint16 DYNAMIC=2\n"
"\n"
"\n"
"uuid_msgs/UniqueID uuid                     # A unique ID of the object generated by the radar.\n"
"\n"
"                                            # Note: The z component of these fields is ignored for 2D tracking.\n"
"geometry_msgs/Point position                # x, y, z coordinates of the centroid of the object being tracked.\n"
"geometry_msgs/Vector3 velocity              # The velocity of the object in each spatial dimension.\n"
"geometry_msgs/Vector3 acceleration          # The acceleration of the object in each spatial dimension.\n"
"geometry_msgs/Vector3 size                  # The object size as represented by the radar sensor eg. length, width, height OR the diameter of an ellipsoid in the x, y, z, dimensions\n"
"                                            # and is from the sensor frame's view.\n"
"uint16 classification                       # An optional classification of the object (see above)\n"
"float32[6] position_covariance              # Upper-triangle covariance about the x, y, z axes\n"
"float32[6] velocity_covariance              # Upper-triangle covariance about the x, y, z axes\n"
"float32[6] acceleration_covariance          # Upper-triangle covariance about the x, y, z axes\n"
"float32[6] size_covariance                  # Upper-triangle covariance about the x, y, z axes\n"
"\n"
"================================================================================\n"
"MSG: uuid_msgs/UniqueID\n"
"# A universally unique identifier (UUID).\n"
"#\n"
"#  http://en.wikipedia.org/wiki/Universally_unique_identifier\n"
"#  http://tools.ietf.org/html/rfc4122.html\n"
"\n"
"uint8[16] uuid\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::radar_msgs::RadarTracks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::radar_msgs::RadarTracks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tracks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarTracks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::radar_msgs::RadarTracks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::radar_msgs::RadarTracks_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tracks[]" << std::endl;
    for (size_t i = 0; i < v.tracks.size(); ++i)
    {
      s << indent << "  tracks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::radar_msgs::RadarTrack_<ContainerAllocator> >::stream(s, indent + "    ", v.tracks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RADAR_MSGS_MESSAGE_RADARTRACKS_H
