(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IPMA_PCAN_DATA_RANGE_CHECK-VAL
          IPMA_PCAN_DATA_RANGE_CHECK
          IPMA_PCAN_MISSING_MSG-VAL
          IPMA_PCAN_MISSING_MSG
          VIN_SIGNAL_COMPARE_FAILURE-VAL
          VIN_SIGNAL_COMPARE_FAILURE
          MODULE_NOT_CONFIGURED_ERROR-VAL
          MODULE_NOT_CONFIGURED_ERROR
          CAR_CFG_NOT_CONFIGURED_ERROR-VAL
          CAR_CFG_NOT_CONFIGURED_ERROR
))