(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_INTERFERENCE_TYPE-VAL
          CAN_INTERFERENCE_TYPE
          CAN_RECOMMEND_UNCONVERGE-VAL
          CAN_RECOMMEND_UNCONVERGE
          CAN_BLOCKAGE_SIDELOBE_FILTER_VAL-VAL
          CAN_BLOCKAGE_SIDELOBE_FILTER_VAL
          CAN_RADAR_ALIGN_INCOMPLETE-VAL
          CAN_RADAR_ALIGN_INCOMPLETE
          CAN_BLOCKAGE_SIDELOBE-VAL
          CAN_BLOCKAGE_SIDELOBE
          CAN_BLOCKAGE_MNR-VAL
          CAN_BLOCKAGE_MNR
          CAN_RADAR_EXT_COND_NOK-VAL
          CAN_RADAR_EXT_COND_NOK
          CAN_RADAR_ALIGN_OUT_RANGE-VAL
          CAN_RADAR_ALIGN_OUT_RANGE
          CAN_RADAR_ALIGN_NOT_START-VAL
          CAN_RADAR_ALIGN_NOT_START
          CAN_RADAR_OVERHEAT_ERROR-VAL
          CAN_RADAR_OVERHEAT_ERROR
          CAN_RADAR_NOT_OP-VAL
          CAN_RADAR_NOT_OP
          CAN_XCVR_OPERATIONAL-VAL
          CAN_XCVR_OPERATIONAL
))