(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_PBL_FIELD_REVISION-VAL
          CAN_PBL_FIELD_REVISION
          CAN_PBL_PROMOTE_REVISION-VAL
          CAN_PBL_PROMOTE_REVISION
          CAN_SW_FIELD_REVISION-VAL
          CAN_SW_FIELD_REVISION
          CAN_SW_PROMOTE_REVISION-VAL
          CAN_SW_PROMOTE_REVISION
          CAN_SW_RELEASE_REVISION-VAL
          CAN_SW_RELEASE_REVISION
          CAN_PBL_RELEASE_REVISION-VAL
          CAN_PBL_RELEASE_REVISION
))