(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_STOP_FREQUENCY_NRML-VAL
          CAN_STOP_FREQUENCY_NRML
          CAN_PRP_FACTOR_NRML-VAL
          CAN_PRP_FACTOR_NRML
          CAN_DESIRED_SWEEP_BW_NRML-VAL
          CAN_DESIRED_SWEEP_BW_NRML
          CAN_RADIATION_CTRL-VAL
          CAN_RADIATION_CTRL
          CAN_STOP_FREQUENCY_NRLL-VAL
          CAN_STOP_FREQUENCY_NRLL
          CAN_PRP_FACTOR_NRLL-VAL
          CAN_PRP_FACTOR_NRLL
          CAN_DESIRED_SWEEP_BW_NRLL-VAL
          CAN_DESIRED_SWEEP_BW_NRLL
))