(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_SENSITIVITY_PROFILE_SELECT-VAL
          CAN_SENSITIVITY_PROFILE_SELECT
          CAN_STOP_FREQUENCY_FRML-VAL
          CAN_STOP_FREQUENCY_FRML
          CAN_STOP_FREQUENCY_FRLL-VAL
          CAN_STOP_FREQUENCY_FRLL
          CAN_PRP_FACTOR_FRML-VAL
          CAN_PRP_FACTOR_FRML
          CAN_PRP_FACTOR_FRLL-VAL
          CAN_PRP_FACTOR_FRLL
          CAN_DESIRED_SWEEP_BW_FRML-VAL
          CAN_DESIRED_SWEEP_BW_FRML
          CAN_DESIRED_SWEEP_BW_FRLL-VAL
          CAN_DESIRED_SWEEP_BW_FRLL
))