(cl:in-package delphi_srr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_TX_DETECT_VALID_LEVEL-VAL
          CAN_TX_DETECT_VALID_LEVEL
          CAN_TX_DETECT_STATUS-VAL
          CAN_TX_DETECT_STATUS
          CAN_TX_DETECT_RANGE_RATE-VAL
          CAN_TX_DETECT_RANGE_RATE
          CAN_TX_DETECT_RANGE-VAL
          CAN_TX_DETECT_RANGE
          CAN_TX_DETECT_ANGLE-VAL
          CAN_TX_DETECT_ANGLE
          CAN_TX_DETECT_AMPLITUDE-VAL
          CAN_TX_DETECT_AMPLITUDE
))