(cl:in-package delphi_srr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_TX_SW_VERSION_HOST-VAL
          CAN_TX_SW_VERSION_HOST
          CAN_TX_PATH_ID_BLIS_IGNORE-VAL
          CAN_TX_PATH_ID_BLIS_IGNORE
          CAN_TX_PATH_ID_BLIS-VAL
          CAN_TX_PATH_ID_BLIS
          CAN_TX_ANGLE_MISALIGNMENT-VAL
          CAN_TX_ANGLE_MISALIGNMENT
          CAN_TX_AUTO_ALIGN_ANGLE-VAL
          CAN_TX_AUTO_ALIGN_ANGLE
))