(cl:in-package delphi_srr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_TX_ALIGNMENT_STATE-VAL
          CAN_TX_ALIGNMENT_STATE
          CAN_TX_INTERFACE_VER_MINOR-VAL
          CAN_TX_INTERFACE_VER_MINOR
          CAN_TX_SW_VERSION_ARM-VAL
          CAN_TX_SW_VERSION_ARM
          CAN_TX_HW_VERSION-VAL
          CAN_TX_HW_VERSION
          CAN_TX_INTERFACE_VERSION-VAL
          CAN_TX_INTERFACE_VERSION
          CAN_TX_SERIAL_NUM-VAL
          CAN_TX_SERIAL_NUM
))