// Generated by gencpp from file delphi_esr_msgs/EsrStatus5.msg
// DO NOT EDIT!


#ifndef DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS5_H
#define DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS5_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_esr_msgs
{
template <class ContainerAllocator>
struct EsrStatus5_
{
  typedef EsrStatus5_<ContainerAllocator> Type;

  EsrStatus5_()
    : header()
    , canmsg()
    , swbatt_a2d(0)
    , ignp_a2d(0)
    , temp1_a2d(0)
    , temp2_a2d(0)
    , supply_5va_a2d(0)
    , supply_5vdx_a2d(0)
    , supply_3p3v_a2d(0)
    , supply_10v_a2d(0)  {
    }
  EsrStatus5_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canmsg(_alloc)
    , swbatt_a2d(0)
    , ignp_a2d(0)
    , temp1_a2d(0)
    , temp2_a2d(0)
    , supply_5va_a2d(0)
    , supply_5vdx_a2d(0)
    , supply_3p3v_a2d(0)
    , supply_10v_a2d(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _canmsg_type;
  _canmsg_type canmsg;

   typedef uint8_t _swbatt_a2d_type;
  _swbatt_a2d_type swbatt_a2d;

   typedef uint8_t _ignp_a2d_type;
  _ignp_a2d_type ignp_a2d;

   typedef uint8_t _temp1_a2d_type;
  _temp1_a2d_type temp1_a2d;

   typedef uint8_t _temp2_a2d_type;
  _temp2_a2d_type temp2_a2d;

   typedef uint8_t _supply_5va_a2d_type;
  _supply_5va_a2d_type supply_5va_a2d;

   typedef uint8_t _supply_5vdx_a2d_type;
  _supply_5vdx_a2d_type supply_5vdx_a2d;

   typedef uint8_t _supply_3p3v_a2d_type;
  _supply_3p3v_a2d_type supply_3p3v_a2d;

   typedef uint8_t _supply_10v_a2d_type;
  _supply_10v_a2d_type supply_10v_a2d;





  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> const> ConstPtr;

}; // struct EsrStatus5_

typedef ::delphi_esr_msgs::EsrStatus5_<std::allocator<void> > EsrStatus5;

typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus5 > EsrStatus5Ptr;
typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus5 const> EsrStatus5ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.canmsg == rhs.canmsg &&
    lhs.swbatt_a2d == rhs.swbatt_a2d &&
    lhs.ignp_a2d == rhs.ignp_a2d &&
    lhs.temp1_a2d == rhs.temp1_a2d &&
    lhs.temp2_a2d == rhs.temp2_a2d &&
    lhs.supply_5va_a2d == rhs.supply_5va_a2d &&
    lhs.supply_5vdx_a2d == rhs.supply_5vdx_a2d &&
    lhs.supply_3p3v_a2d == rhs.supply_3p3v_a2d &&
    lhs.supply_10v_a2d == rhs.supply_10v_a2d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delphi_esr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9be5998c2855516519b427fa839cb6bd";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9be5998c28555165ULL;
  static const uint64_t static_value2 = 0x19b427fa839cb6bdULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_esr_msgs/EsrStatus5";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# ESR Status5\n"
"string      canmsg\n"
"\n"
"uint8       swbatt_a2d\n"
"uint8       ignp_a2d\n"
"uint8       temp1_a2d\n"
"uint8       temp2_a2d\n"
"uint8       supply_5va_a2d\n"
"uint8       supply_5vdx_a2d\n"
"uint8       supply_3p3v_a2d\n"
"uint8       supply_10v_a2d\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canmsg);
      stream.next(m.swbatt_a2d);
      stream.next(m.ignp_a2d);
      stream.next(m.temp1_a2d);
      stream.next(m.temp2_a2d);
      stream.next(m.supply_5va_a2d);
      stream.next(m.supply_5vdx_a2d);
      stream.next(m.supply_3p3v_a2d);
      stream.next(m.supply_10v_a2d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EsrStatus5_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_esr_msgs::EsrStatus5_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canmsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.canmsg);
    s << indent << "swbatt_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.swbatt_a2d);
    s << indent << "ignp_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ignp_a2d);
    s << indent << "temp1_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.temp1_a2d);
    s << indent << "temp2_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.temp2_a2d);
    s << indent << "supply_5va_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.supply_5va_a2d);
    s << indent << "supply_5vdx_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.supply_5vdx_a2d);
    s << indent << "supply_3p3v_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.supply_3p3v_a2d);
    s << indent << "supply_10v_a2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.supply_10v_a2d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS5_H
