// Generated by gencpp from file delphi_esr_msgs/EsrStatus9.msg
// DO NOT EDIT!


#ifndef DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS9_H
#define DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS9_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_esr_msgs
{
template <class ContainerAllocator>
struct EsrStatus9_
{
  typedef EsrStatus9_<ContainerAllocator> Type;

  EsrStatus9_()
    : header()
    , canmsg()
    , avg_pwr_cwblkg(0)
    , sideslip_angle(0.0)
    , serial_num_3rd_byte(0)
    , water_spray_target_id(0)
    , filtered_xohp_acc_cipv(0.0)
    , path_id_acc_2(0)
    , path_id_acc_3(0)  {
    }
  EsrStatus9_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canmsg(_alloc)
    , avg_pwr_cwblkg(0)
    , sideslip_angle(0.0)
    , serial_num_3rd_byte(0)
    , water_spray_target_id(0)
    , filtered_xohp_acc_cipv(0.0)
    , path_id_acc_2(0)
    , path_id_acc_3(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _canmsg_type;
  _canmsg_type canmsg;

   typedef uint16_t _avg_pwr_cwblkg_type;
  _avg_pwr_cwblkg_type avg_pwr_cwblkg;

   typedef float _sideslip_angle_type;
  _sideslip_angle_type sideslip_angle;

   typedef uint8_t _serial_num_3rd_byte_type;
  _serial_num_3rd_byte_type serial_num_3rd_byte;

   typedef uint8_t _water_spray_target_id_type;
  _water_spray_target_id_type water_spray_target_id;

   typedef float _filtered_xohp_acc_cipv_type;
  _filtered_xohp_acc_cipv_type filtered_xohp_acc_cipv;

   typedef uint8_t _path_id_acc_2_type;
  _path_id_acc_2_type path_id_acc_2;

   typedef uint8_t _path_id_acc_3_type;
  _path_id_acc_3_type path_id_acc_3;





  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> const> ConstPtr;

}; // struct EsrStatus9_

typedef ::delphi_esr_msgs::EsrStatus9_<std::allocator<void> > EsrStatus9;

typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus9 > EsrStatus9Ptr;
typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus9 const> EsrStatus9ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.canmsg == rhs.canmsg &&
    lhs.avg_pwr_cwblkg == rhs.avg_pwr_cwblkg &&
    lhs.sideslip_angle == rhs.sideslip_angle &&
    lhs.serial_num_3rd_byte == rhs.serial_num_3rd_byte &&
    lhs.water_spray_target_id == rhs.water_spray_target_id &&
    lhs.filtered_xohp_acc_cipv == rhs.filtered_xohp_acc_cipv &&
    lhs.path_id_acc_2 == rhs.path_id_acc_2 &&
    lhs.path_id_acc_3 == rhs.path_id_acc_3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delphi_esr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "303ebfcbdd8866a01d6c2acd5e4df496";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x303ebfcbdd8866a0ULL;
  static const uint64_t static_value2 = 0x1d6c2acd5e4df496ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_esr_msgs/EsrStatus9";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# ESR Status9\n"
"string      canmsg\n"
"\n"
"uint16      avg_pwr_cwblkg\n"
"float32     sideslip_angle\n"
"uint8       serial_num_3rd_byte\n"
"uint8       water_spray_target_id\n"
"float32     filtered_xohp_acc_cipv\n"
"uint8       path_id_acc_2\n"
"uint8       path_id_acc_3\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canmsg);
      stream.next(m.avg_pwr_cwblkg);
      stream.next(m.sideslip_angle);
      stream.next(m.serial_num_3rd_byte);
      stream.next(m.water_spray_target_id);
      stream.next(m.filtered_xohp_acc_cipv);
      stream.next(m.path_id_acc_2);
      stream.next(m.path_id_acc_3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EsrStatus9_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_esr_msgs::EsrStatus9_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canmsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.canmsg);
    s << indent << "avg_pwr_cwblkg: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.avg_pwr_cwblkg);
    s << indent << "sideslip_angle: ";
    Printer<float>::stream(s, indent + "  ", v.sideslip_angle);
    s << indent << "serial_num_3rd_byte: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.serial_num_3rd_byte);
    s << indent << "water_spray_target_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.water_spray_target_id);
    s << indent << "filtered_xohp_acc_cipv: ";
    Printer<float>::stream(s, indent + "  ", v.filtered_xohp_acc_cipv);
    s << indent << "path_id_acc_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_acc_2);
    s << indent << "path_id_acc_3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_acc_3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS9_H
