// Generated by gencpp from file delphi_esr_msgs/EsrTrackMotionPowerGroup.msg
// DO NOT EDIT!


#ifndef DELPHI_ESR_MSGS_MESSAGE_ESRTRACKMOTIONPOWERGROUP_H
#define DELPHI_ESR_MSGS_MESSAGE_ESRTRACKMOTIONPOWERGROUP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <delphi_esr_msgs/EsrTrackMotionPowerTrack.h>

namespace delphi_esr_msgs
{
template <class ContainerAllocator>
struct EsrTrackMotionPowerGroup_
{
  typedef EsrTrackMotionPowerGroup_<ContainerAllocator> Type;

  EsrTrackMotionPowerGroup_()
    : header()
    , canmsg()
    , rolling_count_2(0)
    , can_id_group(0)
    , tracks()  {
    }
  EsrTrackMotionPowerGroup_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canmsg(_alloc)
    , rolling_count_2(0)
    , can_id_group(0)
    , tracks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _canmsg_type;
  _canmsg_type canmsg;

   typedef uint8_t _rolling_count_2_type;
  _rolling_count_2_type rolling_count_2;

   typedef uint8_t _can_id_group_type;
  _can_id_group_type can_id_group;

   typedef std::vector< ::delphi_esr_msgs::EsrTrackMotionPowerTrack_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::delphi_esr_msgs::EsrTrackMotionPowerTrack_<ContainerAllocator> >> _tracks_type;
  _tracks_type tracks;





  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> const> ConstPtr;

}; // struct EsrTrackMotionPowerGroup_

typedef ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<std::allocator<void> > EsrTrackMotionPowerGroup;

typedef boost::shared_ptr< ::delphi_esr_msgs::EsrTrackMotionPowerGroup > EsrTrackMotionPowerGroupPtr;
typedef boost::shared_ptr< ::delphi_esr_msgs::EsrTrackMotionPowerGroup const> EsrTrackMotionPowerGroupConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.canmsg == rhs.canmsg &&
    lhs.rolling_count_2 == rhs.rolling_count_2 &&
    lhs.can_id_group == rhs.can_id_group &&
    lhs.tracks == rhs.tracks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator1> & lhs, const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delphi_esr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58598630b679d4a2eed0f058be9b1aaa";
  }

  static const char* value(const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58598630b679d4a2ULL;
  static const uint64_t static_value2 = 0xeed0f058be9b1aaaULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_esr_msgs/EsrTrackMotionPowerGroup";
  }

  static const char* value(const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# ESR TrackMotionPower, information common to a group\n"
"string                                      canmsg\n"
"\n"
"uint8                                       rolling_count_2\n"
"uint8                                       can_id_group\n"
"delphi_esr_msgs/EsrTrackMotionPowerTrack[]  tracks\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: delphi_esr_msgs/EsrTrackMotionPowerTrack\n"
"# ESR TrackMotionPower, track-specific information\n"
"uint8  id\n"
"bool   movable_fast\n"
"bool   movable_slow\n"
"bool   moving\n"
"int8   power\n"
;
  }

  static const char* value(const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canmsg);
      stream.next(m.rolling_count_2);
      stream.next(m.can_id_group);
      stream.next(m.tracks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EsrTrackMotionPowerGroup_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_esr_msgs::EsrTrackMotionPowerGroup_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canmsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.canmsg);
    s << indent << "rolling_count_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rolling_count_2);
    s << indent << "can_id_group: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_id_group);
    s << indent << "tracks[]" << std::endl;
    for (size_t i = 0; i < v.tracks.size(); ++i)
    {
      s << indent << "  tracks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::delphi_esr_msgs::EsrTrackMotionPowerTrack_<ContainerAllocator> >::stream(s, indent + "    ", v.tracks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_ESR_MSGS_MESSAGE_ESRTRACKMOTIONPOWERGROUP_H
