(cl:defpackage derived_object_msgs-msg
  (:use )
  (:export
   "<LANE>"
   "LANE"
   "<LANEMODELS>"
   "LANEMODELS"
   "<OBJECT>"
   "OBJECT"
   "<OBJECTARRAY>"
   "OBJECTARRAY"
   "<OBJECTWITHCOVARIANCE>"
   "OBJECTWITHCOVARIANCE"
   "<OBJECTWITHCOVARIANCEARRAY>"
   "OBJECTWITHCOVARIANCEARRAY"
   "<SOLIDPRIMITIVEWITHCOVARIANCE>"
   "SOLIDPRIMITIVEWITHCOVARIANCE"
  ))

