// Generated by gencpp from file neobotix_usboard_msgs/Command.msg
// DO NOT EDIT!


#ifndef NEOBOTIX_USBOARD_MSGS_MESSAGE_COMMAND_H
#define NEOBOTIX_USBOARD_MSGS_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neobotix_usboard_msgs
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : header()
    , command(0)
    , command_data(0)
    , set_num(0)
    , paraset_byte6(0)
    , paraset_byte5(0)
    , paraset_byte4(0)
    , paraset_byte3(0)
    , paraset_byte2(0)
    , paraset_byte1(0)
    , set_active_9to16(0)
    , set_active_1to8(0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command(0)
    , command_data(0)
    , set_num(0)
    , paraset_byte6(0)
    , paraset_byte5(0)
    , paraset_byte4(0)
    , paraset_byte3(0)
    , paraset_byte2(0)
    , paraset_byte1(0)
    , set_active_9to16(0)
    , set_active_1to8(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _command_type;
  _command_type command;

   typedef uint64_t _command_data_type;
  _command_data_type command_data;

   typedef uint8_t _set_num_type;
  _set_num_type set_num;

   typedef uint8_t _paraset_byte6_type;
  _paraset_byte6_type paraset_byte6;

   typedef uint8_t _paraset_byte5_type;
  _paraset_byte5_type paraset_byte5;

   typedef uint8_t _paraset_byte4_type;
  _paraset_byte4_type paraset_byte4;

   typedef uint8_t _paraset_byte3_type;
  _paraset_byte3_type paraset_byte3;

   typedef uint8_t _paraset_byte2_type;
  _paraset_byte2_type paraset_byte2;

   typedef uint8_t _paraset_byte1_type;
  _paraset_byte1_type paraset_byte1;

   typedef uint8_t _set_active_9to16_type;
  _set_active_9to16_type set_active_9to16;

   typedef uint8_t _set_active_1to8_type;
  _set_active_1to8_type set_active_1to8;





  typedef boost::shared_ptr< ::neobotix_usboard_msgs::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neobotix_usboard_msgs::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::neobotix_usboard_msgs::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::neobotix_usboard_msgs::Command > CommandPtr;
typedef boost::shared_ptr< ::neobotix_usboard_msgs::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neobotix_usboard_msgs::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::neobotix_usboard_msgs::Command_<ContainerAllocator1> & lhs, const ::neobotix_usboard_msgs::Command_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command == rhs.command &&
    lhs.command_data == rhs.command_data &&
    lhs.set_num == rhs.set_num &&
    lhs.paraset_byte6 == rhs.paraset_byte6 &&
    lhs.paraset_byte5 == rhs.paraset_byte5 &&
    lhs.paraset_byte4 == rhs.paraset_byte4 &&
    lhs.paraset_byte3 == rhs.paraset_byte3 &&
    lhs.paraset_byte2 == rhs.paraset_byte2 &&
    lhs.paraset_byte1 == rhs.paraset_byte1 &&
    lhs.set_active_9to16 == rhs.set_active_9to16 &&
    lhs.set_active_1to8 == rhs.set_active_1to8;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::neobotix_usboard_msgs::Command_<ContainerAllocator1> & lhs, const ::neobotix_usboard_msgs::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace neobotix_usboard_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neobotix_usboard_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neobotix_usboard_msgs::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neobotix_usboard_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa2adac976b058480751c90ad9fb67d8";
  }

  static const char* value(const ::neobotix_usboard_msgs::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa2adac976b05848ULL;
  static const uint64_t static_value2 = 0x0751c90ad9fb67d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neobotix_usboard_msgs/Command";
  }

  static const char* value(const ::neobotix_usboard_msgs::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message file for Command\n"
"\n"
"std_msgs/Header header\n"
"\n"
"uint8     command                                 \n"
"uint64    command_data                            \n"
"uint8     set_num                                 \n"
"uint8     paraset_byte6                     \n"
"uint8     paraset_byte5                     \n"
"uint8     paraset_byte4                     \n"
"uint8     paraset_byte3                     \n"
"uint8     paraset_byte2                     \n"
"uint8     paraset_byte1                     \n"
"uint8     set_active_9to16                        \n"
"uint8     set_active_1to8                         \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::neobotix_usboard_msgs::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command);
      stream.next(m.command_data);
      stream.next(m.set_num);
      stream.next(m.paraset_byte6);
      stream.next(m.paraset_byte5);
      stream.next(m.paraset_byte4);
      stream.next(m.paraset_byte3);
      stream.next(m.paraset_byte2);
      stream.next(m.paraset_byte1);
      stream.next(m.set_active_9to16);
      stream.next(m.set_active_1to8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neobotix_usboard_msgs::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neobotix_usboard_msgs::Command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "command_data: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.command_data);
    s << indent << "set_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_num);
    s << indent << "paraset_byte6: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paraset_byte6);
    s << indent << "paraset_byte5: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paraset_byte5);
    s << indent << "paraset_byte4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paraset_byte4);
    s << indent << "paraset_byte3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paraset_byte3);
    s << indent << "paraset_byte2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paraset_byte2);
    s << indent << "paraset_byte1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paraset_byte1);
    s << indent << "set_active_9to16: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_active_9to16);
    s << indent << "set_active_1to8: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_active_1to8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEOBOTIX_USBOARD_MSGS_MESSAGE_COMMAND_H
