// Generated by gencpp from file kartech_linear_actuator_msgs/PositionRpt.msg
// DO NOT EDIT!


#ifndef KARTECH_LINEAR_ACTUATOR_MSGS_MESSAGE_POSITIONRPT_H
#define KARTECH_LINEAR_ACTUATOR_MSGS_MESSAGE_POSITIONRPT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kartech_linear_actuator_msgs
{
template <class ContainerAllocator>
struct PositionRpt_
{
  typedef PositionRpt_<ContainerAllocator> Type;

  PositionRpt_()
    : header()
    , shaft_extension(0.0)  {
    }
  PositionRpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , shaft_extension(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _shaft_extension_type;
  _shaft_extension_type shaft_extension;





  typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> const> ConstPtr;

}; // struct PositionRpt_

typedef ::kartech_linear_actuator_msgs::PositionRpt_<std::allocator<void> > PositionRpt;

typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::PositionRpt > PositionRptPtr;
typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::PositionRpt const> PositionRptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator1> & lhs, const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.shaft_extension == rhs.shaft_extension;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator1> & lhs, const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kartech_linear_actuator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc025045a75f313163c8d3ca0cedadf9";
  }

  static const char* value(const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc025045a75f3131ULL;
  static const uint64_t static_value2 = 0x63c8d3ca0cedadf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kartech_linear_actuator_msgs/PositionRpt";
  }

  static const char* value(const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 shaft_extension     # The current shaft position in 0.001\" increments.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.shaft_extension);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionRpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kartech_linear_actuator_msgs::PositionRpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "shaft_extension: ";
    Printer<double>::stream(s, indent + "  ", v.shaft_extension);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARTECH_LINEAR_ACTUATOR_MSGS_MESSAGE_POSITIONRPT_H
