// Generated by gencpp from file kartech_linear_actuator_msgs/ReassignReportIdCmd.msg
// DO NOT EDIT!


#ifndef KARTECH_LINEAR_ACTUATOR_MSGS_MESSAGE_REASSIGNREPORTIDCMD_H
#define KARTECH_LINEAR_ACTUATOR_MSGS_MESSAGE_REASSIGNREPORTIDCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kartech_linear_actuator_msgs
{
template <class ContainerAllocator>
struct ReassignReportIdCmd_
{
  typedef ReassignReportIdCmd_<ContainerAllocator> Type;

  ReassignReportIdCmd_()
    : header()
    , confirm(false)
    , user_report_id(0)
    , use_user_report_id(false)  {
    }
  ReassignReportIdCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , confirm(false)
    , user_report_id(0)
    , use_user_report_id(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _confirm_type;
  _confirm_type confirm;

   typedef uint32_t _user_report_id_type;
  _user_report_id_type user_report_id;

   typedef uint8_t _use_user_report_id_type;
  _use_user_report_id_type use_user_report_id;





  typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ReassignReportIdCmd_

typedef ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<std::allocator<void> > ReassignReportIdCmd;

typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::ReassignReportIdCmd > ReassignReportIdCmdPtr;
typedef boost::shared_ptr< ::kartech_linear_actuator_msgs::ReassignReportIdCmd const> ReassignReportIdCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator1> & lhs, const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.confirm == rhs.confirm &&
    lhs.user_report_id == rhs.user_report_id &&
    lhs.use_user_report_id == rhs.use_user_report_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator1> & lhs, const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kartech_linear_actuator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd2b8bcf6e2eaf63371bf7a3445d195c";
  }

  static const char* value(const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd2b8bcf6e2eaf63ULL;
  static const uint64_t static_value2 = 0x371bf7a3445d195cULL;
};

template<class ContainerAllocator>
struct DataType< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kartech_linear_actuator_msgs/ReassignReportIdCmd";
  }

  static const char* value(const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool confirm\n"
"uint32 user_report_id     # The new user report ID to use. Values 0xFFFEXX and 0xFF00XX are reserved. Setting this to 0xFFFFFFFF will only change the use_user_report_id flag.\n"
"bool use_user_report_id   # Whether to use the user-defined report ID (true) or the default report ID (false).\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.confirm);
      stream.next(m.user_report_id);
      stream.next(m.use_user_report_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReassignReportIdCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kartech_linear_actuator_msgs::ReassignReportIdCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "confirm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirm);
    s << indent << "user_report_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.user_report_id);
    s << indent << "use_user_report_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_user_report_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KARTECH_LINEAR_ACTUATOR_MSGS_MESSAGE_REASSIGNREPORTIDCMD_H
