// Generated by gencpp from file mobileye_560_660_msgs/FixedFoe.msg
// DO NOT EDIT!


#ifndef MOBILEYE_560_660_MSGS_MESSAGE_FIXEDFOE_H
#define MOBILEYE_560_660_MSGS_MESSAGE_FIXEDFOE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mobileye_560_660_msgs
{
template <class ContainerAllocator>
struct FixedFoe_
{
  typedef FixedFoe_<ContainerAllocator> Type;

  FixedFoe_()
    : header()
    , fixed_yaw(0.0)
    , fixed_horizon(0.0)  {
    }
  FixedFoe_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fixed_yaw(0.0)
    , fixed_horizon(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _fixed_yaw_type;
  _fixed_yaw_type fixed_yaw;

   typedef double _fixed_horizon_type;
  _fixed_horizon_type fixed_horizon;





  typedef boost::shared_ptr< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> const> ConstPtr;

}; // struct FixedFoe_

typedef ::mobileye_560_660_msgs::FixedFoe_<std::allocator<void> > FixedFoe;

typedef boost::shared_ptr< ::mobileye_560_660_msgs::FixedFoe > FixedFoePtr;
typedef boost::shared_ptr< ::mobileye_560_660_msgs::FixedFoe const> FixedFoeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator1> & lhs, const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fixed_yaw == rhs.fixed_yaw &&
    lhs.fixed_horizon == rhs.fixed_horizon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator1> & lhs, const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobileye_560_660_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4f93d021949d9d8c671473a5bedf703";
  }

  static const char* value(const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4f93d021949d9d8ULL;
  static const uint64_t static_value2 = 0xc671473a5bedf703ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobileye_560_660_msgs/FixedFoe";
  }

  static const char* value(const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float64 fixed_yaw\n"
"float64 fixed_horizon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fixed_yaw);
      stream.next(m.fixed_horizon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FixedFoe_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobileye_560_660_msgs::FixedFoe_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fixed_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.fixed_yaw);
    s << indent << "fixed_horizon: ";
    Printer<double>::stream(s, indent + "  ", v.fixed_horizon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILEYE_560_660_MSGS_MESSAGE_FIXEDFOE_H
