FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

ARG USER_UID=1000
ARG USER_GID=1000
ARG USER=$(whoami)

ENV DEBIAN_FRONTEND=noninteractive

#use bash instead of sh
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y git python3 python3-pip wget zstd

# Set time zone non-interactively
ENV TZ=America/Chicago
RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apt-get update && apt-get install -y tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://stereolabs.sfo2.cdn.digitaloceanspaces.com/zedsdk/4.2/ZED_SDK_Ubuntu20_cuda11.8_v4.2.4.zstd.run -O zed_sdk.run
RUN chmod +x zed_sdk.run
RUN ./zed_sdk.run -- silent

# Install ROS Noetic
RUN apt-get update && apt-get install -y lsb-release gnupg2
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
RUN wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
RUN apt-key add ros.asc
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ros-noetic-desktop
RUN apt-get install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential python3-catkin-tools
RUN rosdep init
RUN rosdep update

ARG USER
ARG USER_UID
ARG USER_GID

# Create user more safely
RUN groupadd -g ${USER_GID} ${USER} || groupmod -n ${USER} $(getent group ${USER_GID} | cut -d: -f1)
RUN useradd -l -m -u ${USER_UID} -g ${USER_GID} ${USER} || usermod -l ${USER} -m -u ${USER_UID} -g ${USER_GID} $(getent passwd ${USER_UID} | cut -d: -f1)
RUN echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Fix permissions for Python packages
RUN chown -R ${USER}:${USER} /usr/local/lib/python3.8/dist-packages/ \
    && chmod -R u+rw /usr/local/lib/python3.8/dist-packages/

# create ROS Catkin workspace
RUN mkdir -p /catkin_ws/src

# install ROS dependencies and packages
RUN cd /catkin_ws/src && git clone https://github.com/krishauser/POLARIS_GEM_e2.git
RUN cd /catkin_ws/src && git clone --recurse-submodules https://github.com/stereolabs/zed-ros-wrapper.git
RUN cd /catkin_ws/src && git clone https://github.com/astuff/pacmod2.git
   #for some reason the ibeo messages don't work?
RUN cd /catkin_ws/src && git clone https://github.com/astuff/astuff_sensor_msgs.git && rm -rf astuff_sensor_msgs/ibeo_msgs
RUN cd /catkin_ws/src && git clone https://github.com/ros-perception/radar_msgs.git \
   && cd radar_msgs && git checkout noetic 

RUN source /opt/ros/noetic/setup.bash && cd /catkin_ws && rosdep install --from-paths src --ignore-src -r -y
RUN source /opt/ros/noetic/setup.bash && cd /catkin_ws && catkin_make -DCMAKE_BUILD_TYPE=Release -j1

# Copy requirements.txt from host (now relative to parent directory)
COPY requirements.txt /tmp/requirements.txt

# Install Python dependencies
RUN pip3 install -r /tmp/requirements.txt

# Install other Dependencies
RUN apt-get install -y ros-noetic-septentrio-gnss-driver

USER ${USER}

# Add ROS and GEMstack paths to bashrc
RUN echo "source /opt/ros/noetic/setup.bash" >> /home/${USER}/.bashrc
RUN echo "source /catkin_ws/devel/setup.bash" >> /home/${USER}/.bashrc

# BASE END CONFIG
WORKDIR /home/${USER}

ENTRYPOINT [ "/bin/bash", "-l" ]
