(cl:in-package neobotix_usboard_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          COMMAND-VAL
          COMMAND
          ANALOG_DATA_CH4_LOW_BYTE-VAL
          ANALOG_DATA_CH4_LOW_BYTE
          ANALOG_DATA_CH4_HIGH_BITS-VAL
          ANALOG_DATA_CH4_HIGH_BITS
          ANALOG_DATA_CH3_LOW_BYTE-VAL
          ANALOG_DATA_CH3_LOW_BYTE
          ANALOG_DATA_CH3_HIGH_BITS-VAL
          ANALOG_DATA_CH3_HIGH_BITS
          ANALOG_DATA_CH2_LOW_BYTE-VAL
          ANALOG_DATA_CH2_LOW_BYTE
          ANALOG_DATA_CH2_HIGH_BITS-VAL
          ANALOG_DATA_CH2_HIGH_BITS
          ANALOG_DATA_CH1_LOW_BYTE-VAL
          ANALOG_DATA_CH1_LOW_BYTE
          ANALOG_DATA_CH1_HIGH_BITS-VAL
          ANALOG_DATA_CH1_HIGH_BITS
))