(cl:in-package novatel_gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOVATEL_MSG_HEADER-VAL
          NOVATEL_MSG_HEADER
          INS_STATUS-VAL
          INS_STATUS
          POSITION_TYPE-VAL
          POSITION_TYPE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          UNDULATION-VAL
          UNDULATION
          NORTH_VELOCITY-VAL
          NORTH_VELOCITY
          EAST_VELOCITY-VAL
          EAST_VELOCITY
          UP_VELOCITY-VAL
          UP_VELOCITY
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          AZIMUTH-VAL
          AZIMUTH
          LATITUDE_STD-VAL
          LATITUDE_STD
          LONGITUDE_STD-VAL
          LONGITUDE_STD
          ALTITUDE_STD-VAL
          ALTITUDE_STD
          NORTH_VELOCITY_STD-VAL
          NORTH_VELOCITY_STD
          EAST_VELOCITY_STD-VAL
          EAST_VELOCITY_STD
          UP_VELOCITY_STD-VAL
          UP_VELOCITY_STD
          ROLL_STD-VAL
          ROLL_STD
          PITCH_STD-VAL
          PITCH_STD
          AZIMUTH_STD-VAL
          AZIMUTH_STD
          EXTENDED_STATUS-VAL
          EXTENDED_STATUS
          SECONDS_SINCE_UPDATE-VAL
          SECONDS_SINCE_UPDATE
))