(cl:in-package novatel_gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOVATEL_MSG_HEADER-VAL
          NOVATEL_MSG_HEADER
          WEEK-VAL
          WEEK
          SECONDS-VAL
          SECONDS
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          NORTH_VELOCITY-VAL
          NORTH_VELOCITY
          EAST_VELOCITY-VAL
          EAST_VELOCITY
          UP_VELOCITY-VAL
          UP_VELOCITY
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          AZIMUTH-VAL
          AZIMUTH
          STATUS-VAL
          STATUS
))