(cl:in-package novatel_gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NOVATEL_MSG_HEADER-VAL
          NOVATEL_MSG_HEADER
          SOLUTION_STATUS-VAL
          SOLUTION_STATUS
          POSITION_TYPE-VAL
          POSITION_TYPE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          X_SIGMA-VAL
          X_SIGMA
          Y_SIGMA-VAL
          Y_SIGMA
          Z_SIGMA-VAL
          Z_SIGMA
          VELOCITY_SOLUTION_STATUS-VAL
          VELOCITY_SOLUTION_STATUS
          VELOCITY_TYPE-VAL
          VELOCITY_TYPE
          X_VEL-VAL
          X_VEL
          Y_VEL-VAL
          Y_VEL
          Z_VEL-VAL
          Z_VEL
          X_VEL_SIGMA-VAL
          X_VEL_SIGMA
          Y_VEL_SIGMA-VAL
          Y_VEL_SIGMA
          Z_VEL_SIGMA-VAL
          Z_VEL_SIGMA
          BASE_STATION_ID-VAL
          BASE_STATION_ID
          VELOCITY_LATENCY-VAL
          VELOCITY_LATENCY
          DIFF_AGE-VAL
          DIFF_AGE
          SOLUTION_AGE-VAL
          SOLUTION_AGE
          NUM_SATELLITES_TRACKED-VAL
          NUM_SATELLITES_TRACKED
          NUM_SATELLITES_USED_IN_SOLUTION-VAL
          NUM_SATELLITES_USED_IN_SOLUTION
          NUM_GPS_AND_GLONASS_L1_USED_IN_SOLUTION-VAL
          NUM_GPS_AND_GLONASS_L1_USED_IN_SOLUTION
          NUM_GPS_AND_GLONASS_L1_AND_L2_USED_IN_SOLUTION-VAL
          NUM_GPS_AND_GLONASS_L1_AND_L2_USED_IN_SOLUTION
          EXTENDED_SOLUTION_STATUS-VAL
          EXTENDED_SOLUTION_STATUS
          SIGNAL_MASK-VAL
          SIGNAL_MASK
))