(cl:in-package novatel_gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MESSAGE_ID-VAL
          MESSAGE_ID
          UTC_SECONDS-VAL
          UTC_SECONDS
          POSITION_STATUS-VAL
          POSITION_STATUS
          LAT-VAL
          LAT
          LON-VAL
          LON
          LAT_DIR-VAL
          LAT_DIR
          LON_DIR-VAL
          LON_DIR
          SPEED-VAL
          SPEED
          TRACK-VAL
          TRACK
          DATE-VAL
          DATE
          MAG_VAR-VAL
          MAG_VAR
          MAG_VAR_DIRECTION-VAL
          MAG_VAR_DIRECTION
          MODE_INDICATOR-VAL
          MODE_INDICATOR
))