(cl:in-package novatel_gps_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MESSAGE_ID-VAL
          MESSAGE_ID
          UTC_SECONDS-VAL
          UTC_SECONDS
          LAT-VAL
          LAT
          LON-VAL
          LON
          LAT_DIR-VAL
          LAT_DIR
          LON_DIR-VAL
          LON_DIR
          GPS_QUAL-VAL
          GPS_QUAL
          NUM_SATS-VAL
          NUM_SATS
          HDOP-VAL
          HDOP
          ALT-VAL
          ALT
          ALTITUDE_UNITS-VAL
          ALTITUDE_UNITS
          UNDULATION-VAL
          UNDULATION
          UNDULATION_UNITS-VAL
          UNDULATION_UNITS
          DIFF_AGE-VAL
          DIFF_AGE
          STATION_ID-VAL
          STATION_ID
))