# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n-H3mLRZPKqwD0YxM1uSd0F7RwsCAsIA
"""

import numpy as np


# (I + (\phi)_hee) (x,y,z) = (x', y', z')
x,y,z = 0.01, 0.02, 9.78
x_p, y_p, z_p = 0,0,9.8062

# Non-singular matrix A and vector b
A = np.array([[0, z, -y],
              [-z, 0, x],
              [y, -x, 0]])

b = np.array([x_p - x, y_p - y, z_p - z])

# Solve the equation Ax = b
x_lstsq, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

print("Least squares solution:", x_lstsq)

